version: "3"
services:
  db:
    image: postgres:13.2
    environment:
      POSTGRES_DB: search_rs
      POSTGRES_USER: search_rs
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

  adminer:
    image: adminer
    ports:
     - 8080:8080
